"""promote_images

Revision ID: 23436fc36892
Revises: 5b9f1d2c7a4e
Create Date: 2026-01-31 17:44:25.921595

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23436fc36892"
down_revision: str | None = "5b9f1d2c7a4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "yarn_images",
        sa.Column("is_primary", sa.Boolean(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("yarn_images", "is_primary")
    # ### end Alembic commands ###
