"""Add link field to projects and yarns

Revision ID: 4067701db7fd
Revises: 3d61196f82af
Create Date: 2026-01-17 17:12:26.811014

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4067701db7fd"
down_revision: str | None = "3d61196f82af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("link", sa.String(length=2048), nullable=True))
    op.add_column("yarns", sa.Column("link", sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("yarns", "link")
    op.drop_column("projects", "link")
    # ### end Alembic commands ###
