"""Add dye lot to yarns

Revision ID: 6f4b9a3a1c58
Revises: 4067701db7fd
Create Date: 2026-01-24 13:41:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f4b9a3a1c58"
down_revision: str | None = "3b710fa1e811"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("yarns", sa.Column("dye_lot", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("yarns", "dye_lot")
    # ### end Alembic commands ###
