"""Add recommended needles to yarns.

Revision ID: 7c7d5a3c1f2a
Revises: 9f8d2d49f2b1
Create Date: 2026-01-24 16:30:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c7d5a3c1f2a"
down_revision: str | None = "9f8d2d49f2b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "yarns",
        sa.Column("recommended_needles", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("yarns", "recommended_needles")
    # ### end Alembic commands ###
