"""add stitch sample fields

Revision ID: 8b1a9d2f3c4e
Revises: a49c99e32d8a
Create Date: 2026-01-31 22:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b1a9d2f3c4e"
down_revision: Union[str, None] = "a49c99e32d8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("stitch_sample", sa.Text(), nullable=True))
    op.add_column("images", sa.Column("is_stitch_sample", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "is_stitch_sample")
    op.drop_column("projects", "stitch_sample")
    # ### end Alembic commands ###
