"""Add favorite yarns

Revision ID: 8d4968463111
Revises: 20250117_02
Create Date: 2025-12-08 14:19:44.664774

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d4968463111'
down_revision: str | None = '20250117_02'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_yarns',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('yarn_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['yarn_id'], ['yarns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'yarn_id'),
    sa.UniqueConstraint('user_id', 'yarn_id', name='uq_user_favorite_yarn')
    )

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)
        # batch_op.drop_constraint('uq_categories_user_name', type_='unique')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_project_id'))
        batch_op.create_index(batch_op.f('ix_images_id'), ['id'], unique=False)
        batch_op.drop_constraint('fk_images_project_id_projects', type_='foreignkey')
        batch_op.drop_constraint('fk_images_step_id_steps', type_='foreignkey')
        batch_op.create_foreign_key(
            batch_op.f('fk_images_project_id_projects'),
            'projects',
            ['project_id'],
            ['id']
        )
        batch_op.create_foreign_key(
            batch_op.f('fk_images_step_id_steps'),
            'steps',
            ['step_id'],
            ['id']
        )

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.drop_constraint('fk_projects_owner_id_users', type_='foreignkey')
        batch_op.create_foreign_key(
            batch_op.f('fk_projects_owner_id_users'),
            'users',
            ['owner_id'],
            ['id']
        )

    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_steps_project_id'))
        batch_op.create_index(batch_op.f('ix_steps_id'), ['id'], unique=False)
        batch_op.drop_constraint('fk_steps_project_id_projects', type_='foreignkey')
        batch_op.create_foreign_key(
            batch_op.f('fk_steps_project_id_projects'),
            'projects',
            ['project_id'],
            ['id']
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    with op.batch_alter_table('yarn_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yarn_images_id'), ['id'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_yarn_images_yarn_id'),
            ['yarn_id'],
            unique=False
        )

    with op.batch_alter_table('yarns', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_yarns_created_at'),
            ['created_at'],
            unique=False
        )
        batch_op.create_index(batch_op.f('ix_yarns_id'), ['id'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_yarns_owner_id'),
            ['owner_id'],
            unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yarns_owner_id'), table_name='yarns')
    op.drop_index(op.f('ix_yarns_id'), table_name='yarns')
    op.drop_index(op.f('ix_yarns_created_at'), table_name='yarns')
    op.drop_index(op.f('ix_yarn_images_yarn_id'), table_name='yarn_images')
    op.drop_index(op.f('ix_yarn_images_id'), table_name='yarn_images')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(None, 'steps', type_='foreignkey')
    op.create_foreign_key(
        None, 'steps', 'projects', ['project_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_index(op.f('ix_steps_id'), table_name='steps')
    op.create_index(
        op.f('ix_steps_project_id'), 'steps', ['project_id'], unique=False
    )
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(
        None, 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(
        None, 'images', 'steps', ['step_id'], ['id'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        None, 'images', 'projects', ['project_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.create_index(
        op.f('ix_images_project_id'), 'images', ['project_id'], unique=False
    )
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.create_unique_constraint(
        op.f('uq_categories_user_name'), 'categories', ['user_id', 'name']
    )
    op.drop_table('user_favorite_yarns')
    # ### end Alembic commands ###
