"""Add favorite yarns

Revision ID: 8d4968463111
Revises: 20250117_02
Create Date: 2025-12-08 14:19:44.664774

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d4968463111'
down_revision: str | None = '20250117_02'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_yarns',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('yarn_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['yarn_id'], ['yarns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'yarn_id'),
    sa.UniqueConstraint('user_id', 'yarn_id', name='uq_user_favorite_yarn')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite_yarns')
    # ### end Alembic commands ###
