"""Add recommended needles to projects.

Revision ID: 9f8d2d49f2b1
Revises: 6f4b9a3a1c58
Create Date: 2026-01-24 16:10:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f8d2d49f2b1"
down_revision: str | None = "6f4b9a3a1c58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("recommended_needles", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "recommended_needles")
    # ### end Alembic commands ###
