"""remove gauge and recommended needles from project

Revision ID: accb7972e17f
Revises: 55054a3b00c8
Create Date: 2026-02-03 20:32:02.225504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accb7972e17f'
down_revision: Union[str, None] = '55054a3b00c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'gauge_rows')
    op.drop_column('projects', 'gauge_stitches')
    op.drop_column('projects', 'recommended_needles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('recommended_needles', sa.VARCHAR(length=255), nullable=True))
    op.add_column('projects', sa.Column('gauge_stitches', sa.INTEGER(), nullable=True))
    op.add_column('projects', sa.Column('gauge_rows', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
