"""add link archive to yarns

Revision ID: badbda3d0d91
Revises: 23436fc36892
Create Date: 2026-01-31 21:01:58.839998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'badbda3d0d91'
down_revision: Union[str, None] = '23436fc36892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yarns', sa.Column('link_archive', sa.String(length=2048), nullable=True))
    op.add_column('yarns', sa.Column('link_archive_requested_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yarns', 'link_archive_requested_at')
    op.drop_column('yarns', 'link_archive')
    # ### end Alembic commands ###
