"""Rename project comment to notes.

Revision ID: f672f9194075
Revises: accb7972e17f
Create Date: 2026-02-03 20:45:14.640726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f672f9194075'
down_revision: Union[str, None] = 'accb7972e17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.rename_column('comment', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.rename_column('notes', 'comment')
    # ### end Alembic commands ###
