"""Rename project comment to notes.

Revision ID: f672f9194075
Revises: accb7972e17f
Create Date: 2026-02-03 20:45:14.640726

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f672f9194075"
down_revision: str | None = "accb7972e17f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.rename_column("comment", "notes")  # type: ignore[attr-defined]
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.rename_column("notes", "comment")  # type: ignore[attr-defined]
    # ### end Alembic commands ###
